name: Check Fastlane

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Validate Fastlane Supply Metadata
        uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2.1.0
        with:
          fastlaneDir: ./fastlane/metadata/android # optional