name: Generate Sources for Flatpak

on:
  push:
    tags:
      - 'v*'  # This will trigger the workflow for any version tag like v1.0.0, v2.1.3, etc.
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Ensures full history is fetched
          fetch-tags: true

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Generate Sources
        run: |
          pipx install --force git+https://github.com/flatpak/flatpak-builder-tools.git#subdirectory=node
          flatpak-node-generator npm package-lock.json

      - name: Upload generated-sources.json
        uses: actions/upload-artifact@v4
        with:
          name: generated-sources
          path: generated-sources.json