name: Build Electron App (Flatpak) and Cordova APK

on:
  push:
    tags:
      - 'v*'  # This will trigger the workflow for any version tag like v1.0.0, v2.1.3, etc.
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install
          npm run copy:mathjax

      - name: Install Flatpak and required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder xdg-utils libglib2.0-dev libnss3

      - name: Set up Flatpak and install Electron runtime
        run: |
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak update -y
          flatpak install --user -y flathub org.freedesktop.Platform//24.08 org.freedesktop.Sdk//24.08

      - name: Build Electron app as Flatpak
        run: npx electron-builder --linux flatpak

      - name: Upload Flatpak artifact
        uses: actions/upload-artifact@v4
        with:
          name: schulrechner-flatpak
          path: dist/*.flatpak

      # === Android Cordova Build ===

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Cordova
        run: npm install -g cordova

      - name: Prepare and build Cordova project
        run: |
          cordova platform add android
          cordova build android --release "--" --packageType=apk

      - name: Decode Keystore from secret
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > schulrechner.jks

      - name: Find latest Build Tools version
        id: buildtools
        run: |
          LATEST=$(ls -v "$ANDROID_HOME/build-tools" | tail -n 1)
          echo "version=$LATEST" >> $GITHUB_OUTPUT

      - name: Sign the APK with apksigner
        run: |
          BUILD_TOOLS_VERSION=${{ steps.buildtools.outputs.version }}
      
          $ANDROID_HOME/build-tools/$BUILD_TOOLS_VERSION/zipalign -v 4 \
            platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
            platforms/android/app/build/outputs/apk/release/app-release-aligned.apk
      
          $ANDROID_HOME/build-tools/$BUILD_TOOLS_VERSION/apksigner sign \
            --ks schulrechner.jks \
            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
            --out platforms/android/app/build/outputs/apk/release/app-release.apk \
            platforms/android/app/build/outputs/apk/release/app-release-aligned.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: schulrechner-apk
          path: platforms/android/app/build/outputs/apk/release/app-release.apk
